all:
	gcc -g -Wall -O2 -I/gsc/pkg/bio/samtools/installed/ bamreadcount.c -o bam-readcount-test3 -lm -lz -L/gsc/pkg/bio/samtools/installed/ -lbam
debug:
	gcc -g -Wall  -I/gsc/pkg/bio/samtools/installed/ bamreadcount.c -o bam-readcount-test3_debug -lm -lz -L/gsc/pkg/bio/samtools/installed/ -lbam
test4:
	gcc -g -Wall -O2 -I/gsc/pkg/bio/samtools/installed/ bamreadcount.c -o bam-readcount-test4 -lm -lz -L/gsc/pkg/bio/samtools/installed/ -lbam
